# Generated by Django 4.1.1 on 2022-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='name',
        ),
        migrations.AddField(
            model_name='stations',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Station eng name'),
        ),
        migrations.AddField(
            model_name='stations',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Station ru name'),
        ),
        migrations.AddField(
            model_name='stations',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Station uz name'),
        ),
    ]
