# Generated by Django 4.1.1 on 2022-12-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_stations_name_stations_name_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
