# Generated by Django 4.1.1 on 2022-12-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_station_is_uzbek'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=125, null=True, verbose_name='Login')),
                ('password', models.CharField(max_length=125, null=True, verbose_name='Password')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Password',
                'verbose_name_plural': 'User Passwords',
            },
        ),
        migrations.AddField(
            model_name='tguser',
            name='login',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='Sanagacha')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('blocked', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('station_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_notifications', to='main.station', verbose_name='Stansiyadan')),
                ('station_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_stations', to='main.station', verbose_name='Stansiyaga')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tguser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-id',),
            },
        ),
    ]
