# Generated by Django 4.1.1 on 2022-12-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userpassword_tguser_login_tguser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Username'),
        ),
    ]
