# Generated by Django 4.1.1 on 2022-12-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tguser_first_name_alter_tguser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
